### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by PulcioPappi** [MisterHyacinth/Psittacine#2]
Hi, I tried putting this mod in my 200+ modpack, but before even loading the game it crashes. This is the report it gave me, but I couldn't find any mod involved somehow 🤷‍♂️. I also have syntra connector installed.

[crash-2024-10-20_15.35.10-client.txt](https://github.com/user-attachments/files/17450419/crash-2024-10-20_15.35.10-client.txt)

**Comment by digi2303** [comment]
Uhm you sure this is the right crash report?
It says you are on 1.20.1 Forge

**Comment by digi2303** [comment]
This mod is for 1.21 not 1.20.1
